[package]
name = "shopping-cart"
version = "1.0.0"
authors = ["Peter Walser <pwalser@frostnova.ch>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
